package com.rl.financedot.presentation.ui.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF005AB5)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF0072E2)
val onPrimaryContainerLight = Color(0xFFFDFBFF)
val secondaryLight = Color(0xFF465F8A)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFB4CDFE)
val onSecondaryContainerLight = Color(0xFF3E5681)
val tertiaryLight = Color(0xFF8835A8)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFA350C3)
val onTertiaryContainerLight = Color(0xFFFFFAFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF9F9FF)
val onBackgroundLight = Color(0xFF181C22)
val surfaceLight = Color(0xFFF9F9FF)
val onSurfaceLight = Color(0xFF181C22)
val surfaceVariantLight = Color(0xFFDDE2F2)
val onSurfaceVariantLight = Color(0xFF414753)
val outlineLight = Color(0xFF717785)
val outlineVariantLight = Color(0xFFC1C6D6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3038)
val inverseOnSurfaceLight = Color(0xFFEFF0FA)
val inversePrimaryLight = Color(0xFFAAC7FF)
val surfaceDimLight = Color(0xFFD8DAE3)
val surfaceBrightLight = Color(0xFFF9F9FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF1F3FD)
val surfaceContainerLight = Color(0xFFECEDF7)
val surfaceContainerHighLight = Color(0xFFE6E8F1)
val surfaceContainerHighestLight = Color(0xFFE0E2EC)




val primaryDark = Color(0xFFAAC7FF)
val onPrimaryDark = Color(0xFF002F65)
val primaryContainerDark = Color(0xFF0072E2)
val onPrimaryContainerDark = Color(0xFFFDFBFF)
val secondaryDark = Color(0xFFAEC7F8)
val onSecondaryDark = Color(0xFF153059)
val secondaryContainerDark = Color(0xFF2E4771)
val onSecondaryContainerDark = Color(0xFF9DB6E6)
val tertiaryDark = Color(0xFFEDB1FF)
val onTertiaryDark = Color(0xFF530070)
val tertiaryContainerDark = Color(0xFFA350C3)
val onTertiaryContainerDark = Color(0xFFFFFAFF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF10131A)
val onBackgroundDark = Color(0xFFE0E2EC)
val surfaceDark = Color(0xFF10131A)
val onSurfaceDark = Color(0xFFE0E2EC)
val surfaceVariantDark = Color(0xFF414753)
val onSurfaceVariantDark = Color(0xFFC1C6D6)
val outlineDark = Color(0xFF8B919F)
val outlineVariantDark = Color(0xFF414753)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E2EC)
val inverseOnSurfaceDark = Color(0xFF2D3038)
val inversePrimaryDark = Color(0xFF005CB9)
val surfaceDimDark = Color(0xFF10131A)
val surfaceBrightDark = Color(0xFF363941)
val surfaceContainerLowestDark = Color(0xFF0B0E15)
val surfaceContainerLowDark = Color(0xFF181C22)
val surfaceContainerDark = Color(0xFF1C2027)
val surfaceContainerHighDark = Color(0xFF272A31)
val surfaceContainerHighestDark = Color(0xFF32353C)

